name: discount_app
description: The **Discount Calculator** is a simple, offline tool that helps you quickly calculate the final price of a product after applying a discount. This tool is perfect for personal use, allowing you to determine your savings without needing an internet connection or dealing with ads.

version: 1.0.0+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Flavor Management
  flutter_flavorizr: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/